version: '3'
services:
  samba:
    image: dperson/samba
    container_name: samba
    volumes:
      - /:/shared
    command: '-s "shared;/shared"'
    environment:
      TZ: 'EST5EDT'
    networks:
      - default
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
networks:
  default: